#include <raylib.h>
#include <raymath.h>
#include <imgui.h>
#include <rlImGui.h>
#include <string>
#include <iostream>
#include <cmath>

// World Constants
const double G = 6.67430e-11; // Gravitational constant.

double CalculateGM(double mass, double G) { // Function for calculating the standard gravitational parameter (μ). This is gravitational constant multiplied by the mass of the object.
    return(mass*G);
};

void DrawCenteredGrid(float cameraX, float cameraZ)
{
    float spacing = 2.0f;
    int halfLines = 40;
    float extent = halfLines * spacing;
    float centerX = floorf(cameraX / spacing) * spacing;
    float centerZ = floorf(cameraZ / spacing) * spacing;

    for (int i = -halfLines; i <= halfLines; i++)

    {
        float x = centerX + i * spacing;

        DrawLine3D(
            { x, 0.0f, centerZ - extent },
            { x, 0.0f, centerZ + extent },
            WHITE
        );
    }

    for (int i = -halfLines; i <= halfLines; i++)

    {
        float z = centerZ + i*spacing;
        
        DrawLine3D(
            { centerX - extent, 0.0f, z },
            { centerX + extent, 0.0f, z },
            WHITE
        );
    }
}

int main() 
{
    const Color black = {0, 0, 0, 255};

    Camera camera = { 0 };
    camera.position = (Vector3){ 10.0f, 5.0f, 0.0f };
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
    camera.fovy = 45.0f;
    camera.projection = CAMERA_PERSPECTIVE;

    // Celestial Bodies Classes
    class Star {
        public:
            std::string name;
            int radius;
            Vector3 pos;
            Vector3 velocity;
            Vector3 acceleration;
            double mass;
            Color colour;
    };

    class Planet {
        public:
            std::string name;
            int radius;
            Vector3 pos;
            Vector3 velocity;
            Vector3 acceleration;
            double mass;
            Color colour;
    };
    
    // Celestial Bodies Objects
    Star sol;
    sol.name = "Sol";
    sol.radius = 1;
    sol.pos = {0, 0, 0};
    sol.velocity = {0, 0, 0};
    sol.acceleration = {0, 0, 0};
    sol.mass = 1; // Using arbitrary units for no-w
    sol.colour = YELLOW;

    Planet earth;
    earth.name = "Earth";
    earth.radius = 1;
    earth.pos = {0, 0, 20};
    earth.acceleration = {0, 0, 0};
    earth.velocity = {1, 0, 0};
    earth.mass = 1;
    earth.colour = BLUE;

    // Calculations

    // double solGM = CalculateGM(sol.mass, G); // Calculate standard gravitational parameter (μ) for sol. 
    float solGM = 30; // Calculated previously using kepler's third law as simulation *currently* uses arbitrary units

    constexpr int screenWidth = 1920;
    constexpr int screenHeight = 1080;
    
    InitWindow(screenWidth, screenHeight, "Ephemeris-0");
    SetTargetFPS(60);
    rlImGuiSetup(true);


    while (!WindowShouldClose())
    {
        // Camera
        UpdateCamera(&camera, CAMERA_FREE);
        if (IsKeyPressed(KEY_ESCAPE)) DisableCursor(); // update camera logic later. escape just closes the window
        else EnableCursor();

        float dt = GetFrameTime(); // Time step for the simulation, calculated as the time taken to render the last frame. This is used to ensure that the simulation runs at a consistent speed regardless of the frame rate. (description generated by AI)
        float fps = 1.0f / dt;

        Vector3 r = Vector3Subtract(sol.pos, earth.pos); // Tells us the direction and distance from the earth to the sun
        float d = Vector3Length(r); // Compute the distance (magnitude) from earth to sun
        Vector3 dir = Vector3Scale(r, 1.0f/d); // Divide r by d. Leaves us with the direction (for example if r is -40, d would be 40. therefore by dividing, we get -1 (meaning the earth has to take away position to get to the sun))

        // Update Earth position. Can swap this to a function later if I have more objects.

        float a = (float)solGM / (d * d);
        earth.acceleration = Vector3Scale(dir, a);
        earth.velocity = Vector3Add(earth.velocity, Vector3Scale(earth.acceleration, dt));

        earth.pos.x += earth.velocity.x * dt;
        earth.pos.y += earth.velocity.y * dt;
        earth.pos.z += earth.velocity.z * dt;



        // Drawing
        BeginDrawing();
            ClearBackground(black);

            BeginMode3D(camera);
                // DrawGrid(60, 2.0f);
                DrawCenteredGrid(camera.position.x, camera.position.z);
                DrawSphere(sol.pos, sol.radius, sol.colour);
                DrawSphere(earth.pos, earth.radius, earth.colour);
            EndMode3D();

            rlImGuiBegin();
                ImGui::Begin("Debug", 
                nullptr,
                ImGuiWindowFlags_NoDecoration |
                ImGuiWindowFlags_AlwaysAutoResize |
                ImGuiWindowFlags_NoSavedSettings |
                ImGuiWindowFlags_NoFocusOnAppearing |
                ImGuiWindowFlags_NoNav);
                ImGui::Text("Earth Position: (%.2f, %.2f, %.2f)", earth.pos.x, earth.pos.y, earth.pos.z);
                // ImGui::Text("Earth Velocity: (%.2f, %.2f, %.2f)", earth.velocity.x, earth.velocity.y, earth.velocity.z); // Needs to add relative/local velocity. This is global
                ImGui::Text("FPS: %.1f", fps);
                ImGui::End();
            rlImGuiEnd();
        EndDrawing();
    }
    
    rlImGuiShutdown();
    CloseWindow();
}
